# Generated by Django 5.2.8 on 2025-11-22 17:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0002_payments"),
    ]

    operations = [
        migrations.RenameField(
            model_name="payments",
            old_name="payment_amount",
            new_name="payment_sum",
        ),
    ]
