# Generated by Django 5.2.8 on 2025-11-22 18:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("materials", "0002_alter_course_options_alter_lesson_options"),
        ("users", "0003_rename_payment_amount_payments_payment_sum"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="Payments",
            new_name="Payment",
        ),
    ]
