# Generated by Django 5.2.8 on 2025-12-20 12:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0008_alter_payment_payment_date_alter_payment_payment_sum_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="payment",
            name="link",
            field=models.URLField(
                blank=True, max_length=1000, null=True, verbose_name="Ссылка на оплату"
            ),
        ),
    ]
